version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres_db:
        condition: service_healthy
      superset:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - superset_db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # Added line for initialization script

  superset:
    build:
      context: ./superset  # Updated to point to the superset directory
    depends_on:
      - postgres_db
    env_file:
      - ./superset/.env
    environment:
      # You can also set the admin credentials here as environment variables if needed
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=superset
      - SUPERSET_SECRET_KEY=uwBS1V+RsmEiEdy7kkQ3Gcs4FnaaKhYOcqasXWd9uUjZ4ng1tn5XoBCw
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8088 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s
    ports:
      - "8088:8088"
    volumes:
      - superset_data:/home/superset/.superset
      - ./superset/superset_config.py:/app/superset_config.py  # Assuming superset_config.py is in the superset directory

  superset_init:
    build:
      context: ./superset  # Updated to point to the superset directory
    depends_on:
      - postgres_db
      - superset
    env_file:
      - ./superset/.env
    environment:
      # Environment variables for admin credentials can also be specified here if needed
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=superset
      - ADMIN_USERNAME=admin
      - ADMIN_FIRST_NAME=admin
      - ADMIN_LAST_NAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminpassword
      - SUPERSET_SECRET_KEY=uwBS1V+RsmEiEdy7kkQ3Gcs4FnaaKhYOcqasXWd9uUjZ4ng1tn5XoBCw
    volumes:
      - superset_data:/home/superset/.superset
      - ./superset/superset_custom.sh:/app/superset_custom.sh  # Mapping the custom script into the container
  
  alembic:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
    command: /app/backend/migrate.sh


volumes:
  superset_db_data:
  superset_data:
