FROM python:3.9-slim-buster

WORKDIR /app/backend

# Copy the application files
COPY . /app/backend

# Install required system dependencies
RUN apt-get update && \
    apt-get install -y curl postgresql-client build-essential poppler-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
