apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: "prod"
  APP_HOST: "docshow.ai"
  DATABASE_POOL_SIZE: "10"
  DATABASE_POOL_MAX_OVERFLOW: "3"
  DATABASE_LANGCHAIN_POOL_SIZE: "5"
  DATABASE_LANGCHAIN_POOL_MAX_OVERFLOW: "2"
  EMAIL_VERIFICATION_EXPIRE_MINUTES: "15"
  PASSWORD_RESET_EXPIRE_MINUTES: "15"
  SPACES_BUCKET_NAME: "docshowai"
  SPACES_ENDPOINT_URL: "https://docshowai.fra1.digitaloceanspaces.com"
  SPACES_REGION_NAME: "fra1"