apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: registry.digitalocean.com/docshow-ai/migration-prod:latest
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: migration-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_URL
      restartPolicy: OnFailure