apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: registry.digitalocean.com/docshow-ai/migration-prod:latest
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: AZURE_CLIENT_ID
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: AZURE_TENANT_ID
        - name: AZURE_APP_VALUE
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: AZURE_APP_VALUE
        - name: AZURE_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: AZURE_APP_SECRET
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_URL
        - name: DATABASE_POOL_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_POOL_URL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET_KEY
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-api-key
              key: SENDGRID_API_KEY
        - name: SPACES_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-access-key
              key: SPACES_ACCESS_KEY
        - name: SPACES_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-secret-access-key
              key: SPACES_SECRET_ACCESS_KEY
      restartPolicy: OnFailure