name: Python Code Quality Check

on: 
  pull_request:
    paths:
      - 'backend/**'

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install black flake8 mypy

    - name: Check Python code formatting with Black
      run: black --check backend/

    - name: Check Python code style with Flake8
      run: flake8 backend/

    - name: Run Mypy Type Checking
      run: mypy backend/
