name: Python Code Quality Check

on: 
  pull_request:
    paths:
      - 'backend/**'

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install black flake8 mypy isort

    - name: Check Python code formatting with Black
      run: black --check --exclude backend/alembic/versions backend/

    - name: Check Python code style with Flake8
      run: flake8 --exclude=backend/alembic/versions backend/

    - name: Run Mypy Type Checking
      run: mypy --ignore-missing-imports --exclude backend/alembic/versions backend/
    
    - name: Check Python import order with isort
      run: isort --check-only --exclude backend/alembic/versions backend/
